name: Build Scoop Artifact
run-name: ${{ github.actor }} Build Scoop.sh artifact.
on: push
jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      
      - name: Scoop setup
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
          Invoke-RestMethod get.scoop.sh -outfile 'install.ps1'
          ./install.ps1 -RunAsAdmin
          scoop update
          New-Item -Path 'artifact' -ItemType Directory
          $scoop_zip = "artifact\wtp-scoop.zip"
          $scoop_path = $HOME + "\scoop"
          Compress-Archive -Path $scoop_path -D $scoop_zip

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          name: wtb-scoop.${{ github.ref }}.zip
          artifacts: "artifact/wtp-scoop.zip"
      